project:
  type: website
  output-dir: docs

website:
  title: "Zpracovávání výzkumných dat v R"
  navbar:
    left:
      - href: index.qmd
        text: hlavní strana
        aria-label: pokus
        icon: github
      - href: about.qmd
        icon: github
      - href: zkouška.qmd
        text: zkouším navabr

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

