project:
  type: website
  output-dir: docs

website:
  title: "Zpracovávání výzkumných dat v R"
  navbar:
    left:
      - href: index.qmd
        aria-label: pokus
        icon: github
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

