project:
  type: website
  output-dir: docs

website:
  title: "Zpracovávání výzkumných dat v R"
  navbar:
    left:
      - href: index.qmd
        icon: github
      - href: about.qmd
        icon: github
      - href: zkouška.qmd
        text: zkouším navabr
      - href: mailto:lucie.hoskova@ruk.cuni.cz
        icon: envelope-at
        aria-label: alt text

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

