---
title: "Sylabus"
---

## 1. Úvodní hodina (15.09.2026)

-   orientace v IDE [RStudio](https://posit.co/download/rstudio-desktop)
-   projekty a organizace skriptů
-   nápověda
-   operátory
-   ukládání do proměnných
-   datové typy v R

## 2. Datové struktury (29.09.2026)

-   úvod do funkcí
-   datové struktury v R
-   faktory
-   práce s balíčky

## 3. Indexace (13.10.2026)

-   indexace pomocí base R
-   indexace pomocí [`dplyr`](https://dplyr.tidyverse.org/)
-   hodnoty vs struktury
-   pipes

## 4. Transformace dat (27.10.2026)

-   načítání dat do R
-   kontrola dat
-   balíček [`dplyr`](https://dplyr.tidyverse.org/)
-   tidy data
-   čas a datum

## 5. Funkce (10.11.2026)

-   syntax funkce
-   tvorba vlastní funkce
-   cykly
-   funkce apply() a celá *apply* rodina funkcí
-   vektorizace vs. itinerární přístup

## 6. Základy vizualizace dat a práce s grafy v R (24.11.2026)

-   přemýšlení nad účelem tvorby grafu
-   bodové, čárové a sloupcové grafy
-   základní vizualizace v R
-   úvod do vizualizace pomocí balíčku [`ggplot2`](https://ggplot2.tidyverse.org/)

## 7. Pokročilá vizualizace dat (08.12.2026)

-   boxploty
-   histogramy
-   denseploty
-   heat mapy
-   violin grafy
-   časové řady

## 8. Mapy, 3D a interaktivní grafy (05.01.2026)

-   prostorová data v R
-   bodové mapy
-   chloropleth mapy
-   3D grafy
-   interaktivní grafy

## 9. Typy dat a deskriptivní statistika (19.01.2027)

-   kvalitativní vs kvantitivní data
-   nominální, ordinální, intervalová, poměrová, diskrétní a spojitá data
-   základy popisné statistiky
-   průměr, medián, mode
-   míry variability

## 10. Úvod do inferenční statistiky (02.02.2027)

-   populace, výběr
-   určování normality dat
-   parametrické testy
-   t-testy

## 11. Analýza kategoriálních dat, korelace a regrese (16.02.2027)

-   kontingenční tabulka
-   neparametrické testy
-   chí-kvadrát
-   Pearson/Spearman korelace
-   regrese
